# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: 齐琦 Qi QI's Web Portal
email: qqi@hainanu.edu.cn
description: >- # this means to ignore newlines until "baseurl:"
  "All great literature is one of two stories;  a man goes on a journey or a stranger comes to town."-- Leo Tolstoy
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: qiziqi
github_username:  qiqi789
facebook_username: qiqi789
google_analytics: UA-12306391-3
show_excerpts: true

# Build settings
markdown: kramdown
# theme: jekyll-theme-architect
theme: minima
repository: "qiq789/qiqi789.github.io"
plugins:
  - jekyll-feed
header_pages:
  - research.md
  - research/venues.md
  - contact.md
  - about.md

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
